// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/17/2026, 10:01:48 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/plugins/**/*.{js,ts,mjs}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/composables/**/*.{js,ts,mjs}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/utils/**/*.{js,ts,mjs}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/mnt/34b710d8-4fad-4cee-93d1-2fc8815a5df5/home/dev/racer/nuxt-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;